import type { BSDayData, LocaleType } from '../types';

export const TITHI_NE_MAP: Record<string, string> = {
  'Pratipada': 'प्रतिपदा',
  'Dvitiya': 'द्वितीया',
  'Tritiya': 'तृतीया',
  'Chaturthi': 'चतुर्थी',
  'Panchami': 'पञ्चमी',
  'Shashthi': 'षष्ठी',
  'Saptami': 'सप्तमी',
  'Ashtami': 'अष्टमी',
  'Navami': 'नवमी',
  'Dashami': 'दशमी',
  'Ekadashi': 'एकादशी',
  'Dwadashi': 'द्वादशी',
  'Trayodashi': 'त्रयोदशी',
  'Chaturdashi': 'चतुर्दशी',
  'Purnima': 'पूर्णिमा',
  'Amavasya': 'औंसी',
  'Aunsi': 'औंसी',
};

export const PAKSHA_NE_MAP: Record<string, string> = {
  'Shukla': 'शुक्ल',
  'Krishna': 'कृष्ण',
};

export const NAKSHATRA_NE_MAP: Record<string, string> = {
  'Ashwini': 'अश्विनी',
  'Bharani': 'भरणी',
  'Krittika': 'कृत्तिका',
  'Rohini': 'रोहिणी',
  'Mrigashirsha': 'मृगशिरा',
  'Ardra': 'आर्द्रा',
  'Punarvasu': 'पुनर्वसु',
  'Pushya': 'पुष्य',
  'Ashlesha': 'अश्लेषा',
  'Magha': 'मघा',
  'Purva Phalguni': 'पूर्व फाल्गुनी',
  'Uttara Phalguni': 'उत्तर फाल्गुनी',
  'Hasta': 'हस्त',
  'Chitra': 'चित्रा',
  'Swati': 'स्वाति',
  'Vishakha': 'विशाखा',
  'Anuradha': 'अनुराधा',
  'Jyeshtha': 'ज्येष्ठा',
  'Mula': 'मूला',
  'Purva Ashadha': 'पूर्वाषाढा',
  'Uttara Ashadha': 'उत्तराषाढा',
  'Shravana': 'श्रवण',
  'Dhanishta': 'धनिष्ठा',
  'Shatabhisha': 'शतभिषा',
  'Purva Bhadrapada': 'पूर्व भाद्रपदा',
  'Uttara Bhadrapada': 'उत्तर भाद्रपदा',
  'Revati': 'रेवती',
};

export const YOGA_NE_MAP: Record<string, string> = {
  'Vishkumbha': 'विष्कम्भ',
  'Priti': 'प्रीति',
  'Ayushman': 'आयुष्मान',
  'Saubhagya': 'सौभाग्य',
  'Shobhana': 'शोभन',
  'Atiganda': 'अतिगण्ड',
  'Sukarma': 'सुकर्मा',
  'Dhriti': 'धृति',
  'Shoola': 'शूल',
  'Ganda': 'गण्ड',
  'Vriddhi': 'वृद्धि',
  'Dhruva': 'ध्रुव',
  'Vyaghata': 'व्याघात',
  'Harsha': 'हर्ष',
  'Vajra': 'वज्र',
  'Siddhi': 'सिद्धि',
  'Vyatipata': 'व्यतीपात',
  'Variyana': 'वरीयान',
  'Parigha': 'परिघ',
  'Shiva': 'शिव',
  'Siddha': 'सिद्ध',
  'Sadhya': 'साध्य',
  'Shubha': 'शुभ',
  'Shukla': 'शुक्ल',
  'Brahma': 'ब्रह्म',
  'Indra': 'इन्द्र',
  'Vaidhriti': 'वैधृति',
};

export const KARANA_NE_MAP: Record<string, string> = {
  'Bava': 'बव',
  'Balava': 'बालव',
  'Kaulava': 'कौलव',
  'Taitila': 'तैतिल',
  'Garaja': 'गर',
  'Vanija': 'वणिज',
  'Vishti': 'विष्टि',
  'Shakuni': 'शकुनि',
  'Chatushpada': 'चतुष्पद',
  'Naga': 'नाग',
  'Kimstughna': 'किस्तुघ्न',
};

export const FESTIVAL_NE_MAP: Record<string, string> = {
  "Matatirtha Aunsi (Mothers' Day)": "मातातीर्थ औंसी (आमाको मुख हेर्ने दिन)",
  "Buddha Jayanti / Ubhauli Parva": "बुद्ध जयन्ती / उभौली पर्व",
  "Buddha Jayanti": "बुद्ध जयन्ती",
  "Sithi Nakha": "सिथि नखः",
  "Guru Purnima": "गुरु पूर्णिमा",
  "Nag Panchami": "नाग पञ्चमी",
  "Raksha Bandhan / Janai Purnima / Kwati Khane Din / Rishi Tarpani / Sanskrit Diwas": "रक्षा बन्धन / जनै पूर्णिमा / क्वाँटी खाने दिन / ऋषितर्पणी / संस्कृत दिवस",
  "Janai Purnima / Raksha Bandhan / Kwati Pune": "जनै पूर्णिमा / रक्षाबन्धन / क्वाँटी पुन्ही",
  "Janai Purnima / Raksha Bandhan": "जनै पूर्णिमा / रक्षाबन्धन",
  "Gai Jatra": "गाईजात्रा",
  "Krishna Janmashtami / Gaura Parva": "श्रीकृष्ण जन्माष्टमी / गौरा पर्व",
  "Krishna Janmashtami": "श्रीकृष्ण जन्माष्टमी",
  "Kushe Aunsi (Fathers' Day)": "कुशे औंसी (बाबुको मुख हेर्ने दिन)",
  "Dar Khane Din": "दर खाने दिन",
  "Haritalika Teej": "हरितालिका तीज (महिला बिदा)",
  "Teej": "हरितालिका तीज",
  "Ganesh Chaturthi": "गणेश चतुर्थी",
  "Rishi Panchami": "ऋषि पञ्चमी",
  "Indra Jatra / Ananta Chaturdashi": "इन्द्रजात्रा / अनन्त चतुर्दशी",
  "Indra Jatra": "इन्द्रजात्रा",
  "Jitiya Parva": "जितिया पर्व (महिला बिदा)",
  "Sohra Shraddha Samapti (Mahalaya)": "सोह्र श्राद्ध समाप्ति (महालय)",
  "Ghatasthapana": "घटस्थापना (नवरात्र आरम्भ)",
  "Fulpati": "फूलपाती",
  "Maha Ashtami": "महा अष्टमी (कालरात्रि)",
  "Maha Navami": "महा नवमी",
  "Vijaya Dashami": "विजया दशमी (बडा दशैं टीका)",
  "Papankusha Ekadashi": "पापाङ्कुशा एकादशी",
  "Dashain Holiday": "दशैं बिदा",
  "Kojagrat Purnima": "कोजाग्रत पूर्णिमा (दशैं समापन)",
  "Kag Tihar": "काग तिहार (यमपञ्चक आरम्भ)",
  "Kukur Tihar": "कुकुर तिहार / नरक चतुर्दशी",
  "Laxmi Puja": "लक्ष्मी पूजा / दीपमालिका",
  "Govardhan Puja / Mha Puja / Gai Puja": "गोवर्धन पूजा / म्ह पूजा / गाई पूजा / हली तिहार",
  "Bhai Tika": "भाइटीका / किजा पूजा",
  "Tihar Holiday": "तिहार बिदा",
  "Chhath Puja": "छठ पर्व",
  "Haribodhini Ekadashi / Tulsi Bibaha": "हरिबोधिनी एकादशी (ठूली एकादशी) / तुलसी विवाह",
  "Bala Chaturdashi": "बाला चतुर्दशी",
  "Bibaha Panchami": "विवाह पञ्चमी",
  "Udhauli Parva / Yomari Punhi": "उधौली पर्व / योमरी पुन्ही",
  "Sonam Lhosar": "सोनाम ल्होसार",
  "Basanta Panchami / Saraswati Puja": "वसन्त पञ्चमी / सरस्वती पूजा (श्रीपञ्चमी)",
  "Maha Shivaratri": "महाशिवरात्रि / सेना दिवस",
  "Gyalpo Lhosar": "ग्याल्पो ल्होसार",
  "Holi / Phagu Purnima (Hilly)": "होली / फागु पूर्णिमा (पहाडी)",
  "Holi / Phagu Purnima (Terai)": "होली / फागु पूर्णिमा (तराई)",
  "Holi / Phagu Purnima": "होली / फागु पूर्णिमा",
  "Holi": "होली",
  "Ghode Jatra": "घोडे जात्रा",
  "Chaite Dashain": "चैते दशैं",
  "Ram Navami": "रामनवमी",
  "Dashain": "दशैँ",
  "Tihar": "तिहार",
};

export const EVENT_NE_MAP: Record<string, string> = {
  "Nepali New Year / Biska Jatra": "नयाँ वर्ष / बिस्का जात्रा",
  "Nepali New Year": "नयाँ वर्ष",
  "Loktantra Diwas": "लोकतन्त्र दिवस",
  "Loktantra Day": "लोकतन्त्र दिवस",
  "Republic Day (Ganatantra Diwas)": "गणतन्त्र दिवस",
  "Republic Day": "गणतन्त्र दिवस",
  "Rastriya Dhan Diwas": "राष्ट्रिय धान दिवस (असार १५)",
  "Shrawan Sankranti / Luto Falne Din": "साउने संक्रान्ति / लुतो फाल्ने दिन",
  "Shrawan Sankranti": "साउने संक्रान्ति",
  "Kheer Khane Din": "खीर खाने दिन",
  "Bhadra Sankranti": "भाद्र संक्रान्ति",
  "Ashwin Sankranti / Bishwakarma Puja": "असोज संक्रान्ति / विश्वकर्मा पूजा",
  "Constitution Day (Sambidhan Diwas)": "संविधान दिवस",
  "Constitution Day": "संविधान दिवस",
  "Kartik Sankranti": "कात्तिक संक्रान्ति",
  "Mangsir Sankranti": "मंसिर संक्रान्ति",
  "Poush Sankranti": "पुष संक्रान्ति",
  "Tamu Lhosar": "तमु ल्होसार",
  "National Unity Day (Prithvi Jayanti)": "राष्ट्रिय एकता दिवस (पृथ्वी जयन्ती)",
  "National Unity Day": "राष्ट्रिय एकता दिवस",
  "Maghe Sankranti / Maghi Parva": "माघे संक्रान्ति / माघी पर्व",
  "Maghe Sankranti": "माघे संक्रान्ति",
  "Martyrs' Day (Shahid Diwas)": "शहीद दिवस",
  "Martyrs' Day": "शहीद दिवस",
  "Falgun Sankranti": "फागुन संक्रान्ति",
  "National Democracy Day (Prajatantra Diwas)": "राष्ट्रिय प्रजातन्त्र दिवस",
  "National Democracy Day": "राष्ट्रिय प्रजातन्त्र दिवस",
  "Chaitra Sankranti": "चैत संक्रान्ति",
  "Dashain Holiday": "दशैं बिदा",
  "Tihar Holiday": "तिहार बिदा",
  "International Women's Day (Nari Diwas)": "अन्तर्राष्ट्रिय महिला दिवस",
  "International Women's Day": "अन्तर्राष्ट्रिय महिला दिवस",
  "Nari Divas": "नारी दिवस",
  "International Labour Day (Majdoor Diwas)": "अन्तर्राष्ट्रिय श्रमिक दिवस",
  "International Labour Day": "श्रमिक दिवस",
  "Earth Day": "पृथ्वी दिवस",
  "Christmas Day": "क्रिसमस डे",
  "International New Year": "अन्तर्राष्ट्रिय नयाँ वर्ष",
  "World Environment Day": "विश्व वातावरण दिवस",
  "International Yoga Day": "अन्तर्राष्ट्रिय योग दिवस",
};

export function localizeBSDayData(data: BSDayData, locale: LocaleType): BSDayData {
  if (locale !== 'ne') {
    return data;
  }

  return {
    ...data,
    tithi: TITHI_NE_MAP[data.tithi] ?? data.tithi,
    paksha: PAKSHA_NE_MAP[data.paksha] ?? data.paksha,
    nakshatra: NAKSHATRA_NE_MAP[data.nakshatra] ?? data.nakshatra,
    yoga: YOGA_NE_MAP[data.yoga] ?? data.yoga,
    karana: KARANA_NE_MAP[data.karana] ?? data.karana,
    festivals: (data.festivals ?? []).map((f) => FESTIVAL_NE_MAP[f] ?? f),
    events: (data.events ?? []).map((e) => EVENT_NE_MAP[e] ?? e),
  };
}
